### ISSUE TITLE
Is Java 21 required here?

### ISSUE THREAD

**Issue by Vest** [PCGen/pcgen-base#430]
Hi @karianna,

do we have to upgrade this project to Java 21?
Does it make sense to join this repo with the main one? I am new here, never asked this question, but what is stored here?

Thanks,
Vest

**Comment by karianna** [comment]
We can actually probably archive or delete this repo.  The code was merged into the main one some time ago.  This repo *may* have some stuff in it that's ahead but incomplete. We can do a stock take and see

**Comment by karianna** [comment]
Note we would need to change the main project to no longer reference a the jar files built out of old tags from this repo...

**Comment by Vest** [comment]
Ah, ok. I understood. 
I can take a look later, what happens, if the dependency to this repo is removed from the main PCGen.
